name: services

services:
  mlflow:
    container_name: mlflow
    hostname: mlflow
    build:
      dockerfile: Dockerfile
      context: ./docker/mlflow
    env_file:
      - ./env/db.env
      - ./env/mlflow.env
    ports:
      - 8000:8000
    networks:
      - taxi
    # depends_on:
    #   - db

  migration:
    container_name: migration
    hostname: migration
    build:
      dockerfile: Dockerfile
      context: ./docker/alembic
    env_file:
      - ./env/db.env
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./src/code/model:/app/src/code/model
    command: alembic upgrade head
    networks:
      - taxi

networks:
  taxi:
    external: true
