name: db

services:
  db:
    container_name: db
    hostname: db
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - taxi

  migration:
    container_name: migration
    hostname: migration
    build:
      context: .
      dockerfile: ./docker/alembic/Dockerfile
    env_file:
      - ./env/db.env
      - ./env/airflow.env
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./sql:/app/sql
    command: alembic upgrade head
    user: "1000:0"
    networks:
      - taxi

  redis:
    container_name: redis
    hostname: redis
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    networks:
      - taxi

volumes:
  postgres-db-volume:

networks:
  taxi:
    external: true
