name: airflow

x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.0}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
  env_file:
    - ./env/airflow.env
  volumes:
    - ${AIRFLOW_PROJ_DIR:-./src}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-./src}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-./src}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-./src}/plugins:/opt/airflow/plugins
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    db:
      condition: service_healthy

services:
  airflow-webserver:
    <<: *airflow-common
    command: webserver -H 0.0.0.0 -p 8080
    ports:
      - 8080:8080
