name: services

services:
  mlflow:
    container_name: mlflow
    hostname: mlflow
    build:
      dockerfile: Dockerfile
      context: ./docker/mlflow
    env_file:
      - ./env/db.env
      - ./env/mlflow.env
    ports:
      - 8000:8000
    networks:
      - taxi

  migration:
    container_name: migration
    hostname: migration
    build:
      context: .
      dockerfile: ./docker/alembic/Dockerfile
    env_file:
      - ./env/db.env
      - ./env/airflow.env
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./sql:/app/sql
    command: alembic upgrade head
    networks:
      - taxi

  backend:
    container_name: backend
    hostname: backend
    build:
      dockerfile: ./docker/backend/Dockerfile
      context: .
    env_file:
      - ./env/airflow.env
      - ./env/db.env
      - ./env/mlflow.env
    volumes:
      - ./src/app/backend/:/app
    command: fastapi dev --port 7000 --host 0.0.0.0 --reload main.py
    ports:
      - 7000:7000
    networks:
      - taxi

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: .
    volumes:
      - ./src/app/frontend/:/app/
    command: streamlit run app.py --server.address 0.0.0.0 --server.port 9000
    ports:
      - 9000:9000
    networks:
      - taxi

  grafana:
    container_name: grafana
    hostname: grafana
    user: "472"
    image: grafana/grafana
    volumes:
      - ./src/config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    ports:
      - 3000:3000
    networks:
      - taxi

networks:
  taxi:
    external: true
