name: nyc-taxi

services:
  db:
    container_name: db
    hostname: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

  mlflow:
    container_name: mlflow
    hostname: mlflow
    build:
      dockerfile: Dockerfile
      context: ./docker/mlflow
    env_file:
      - ./env/db.env
      - ./env/mlflow.env
