name: nyc-taxi

services:
  db:
    container_name: db
    hostname: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  mlflow:
    container_name: mlflow
    hostname: mlflow
    build:
      dockerfile: Dockerfile
      context: ./docker/mlflow
    env_file:
      - ./env/db.env
      - ./env/mlflow.env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres-db-volume:
