[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "taxi_db"
version = "0.0.1"
dependencies = [
    "SQLAlchemy==1.4.53",
    "psycopg2-binary==2.9.9"
]
