from enum import Enum


class GeometryType(Enum):
    POINT = 'POINT'
    LINESTRING = 'LINESTRING'
    POLYGON = 'POLYGON'
    MULTIPOINT = 'MULTIPOINT'
    MULTILINESTRING = 'MULTILINESTRING'
    MULTIPOLYGON = 'MULTIPOLYGON'
    GEOMETRYCOLLECTION = 'GEOMETRYCOLLECTION'
